# Generated by Django 6.0.3 on 2026-03-21 01:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='A brief description of the genre.')),
                ('color', models.CharField(help_text='Hexadecimal color code for the genre (e.g., #FF5733).', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(help_text='A brief summary of the movie plot.')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the movie in minutes.')),
                ('release_at', models.DateField(help_text='The date when the movie was released.')),
                ('rating', models.CharField(help_text="The movie's rating (e.g., PG-13, R, etc.).", max_length=5)),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
                'ordering': ['-release_at'],
            },
        ),
    ]
