# Generated by Django 6.0.3 on 2026-03-21 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(help_text='The date and time when the showtime starts.')),
                ('language', models.CharField(help_text='The language in which the showtime is conducted.', max_length=50)),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular'), ('PREVIEW', 'Preview'), ('PREMIERE', 'Premiere')], help_text='The type of showtime (Regular, Preview, Premiere).', max_length=50)),
                ('movie', models.ForeignKey(help_text='The movie associated with this showtime.', on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movie.movie')),
                ('theater', models.ForeignKey(help_text='The theater where this showtime is taking place.', on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theater.theater')),
            ],
            options={
                'verbose_name': 'Showtime',
                'verbose_name_plural': 'Showtimes',
                'db_table': 'showtime',
            },
        ),
    ]
