# Generated by Django 6.0.3 on 2026-03-21 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('STANDARD', 'Standard'), ('IMAX', 'IMAX'), ('3D', '3D')], help_text='The type of theater (Standard, IMAX, 3D).', max_length=50)),
            ],
            options={
                'verbose_name': 'Theater',
                'verbose_name_plural': 'Theaters',
                'db_table': 'theater',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row', models.CharField(help_text='The row identifier (e.g., A, B, C).', max_length=5)),
                ('number', models.PositiveIntegerField(help_text='The seat number within the row.')),
                ('kind', models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('ACCESSIBLE', 'Accessible')], help_text='The type of seat (Regular, VIP, Accessible).', max_length=50)),
                ('theater', models.ForeignKey(help_text='The theater to which this seat belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theater.theater')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'db_table': 'seat',
            },
        ),
    ]
